version: '3.9'

services:
  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: agents
      POSTGRES_PASSWORD: postgres
